### ISSUE TITLE
the size of the image features

### ISSUE THREAD

**Issue by Yxs-160** [FomalhautB/3D-RETR#3]
Thanks for this work, I really enjoyed reading your paper!
I have a question about the size of the image features which are output from transformer encoder. i would appreciate it if you can help me!@FomalhautB
![image](https://user-images.githubusercontent.com/62494818/150330697-c1a4921f-4651-4f8a-b50a-852e67df4d6a.png)

**Comment by fomalhautb** [comment]
Hi, nice to hear that you like our paper. What is your question exactly?

**Comment by Yxs-160** [comment]
> Hi, nice to hear that you like our paper. What is your question exactly?

can you tell me the specific size of each image feature output from encoder?

**Comment by fomalhautb** [comment]
The encoder is just a VIT model without the MLP head. So for `N` images, the base model encoder output shape is `N x 16^2 x 768`, or `N x 16 x 16 x 768` after resizing to 2d image shape. After the image-wise average operation, the shape is `16 x 16 x 768`.

For more details, you can just print the shape in the code.

**Comment by Yxs-160** [comment]
Thank you for your fast reply! let me have a look

**Comment by Yxs-160** [comment]
Hello, when i run your codes, i meet some problems, i could not solve them, could you help me?
`$ python train.py --model_path SHAPENET_VOXEL --image_path SHAPENET_IMAGE --annot_path data/ShapeNet.json --transformer_config config/3d-retr-s.yaml --gpus 2
{   'accelerator': None,
    'accumulate_grad_batches': 1,
    'amp_backend': 'native',
    'amp_level': 'O2',
    'annot_path': 'data/ShapeNet.json',
    'auto_lr_find': False,
    'auto_scale_batch_size': False,
    'auto_select_gpus': False,
    'background': (0, 0, 0),
    'benchmark': False,
    'check_val_every_n_epoch': 1,
    'checkpoint_callback': True,
    'continue_from': None,
    'data_aug': False,
    'default_root_dir': None,
    'deterministic': False,
    'distributed_backend': None,
    'experiment_name': '3D-RETR',
    'fast_dev_run': False,
    'flush_logs_every_n_steps': 100,
    'gpus': 2,
    'gradient_clip_algorithm': 'norm',
    'gradient_clip_val': 0.0,
    'image_path': 'SHAPENET_IMAGE',
    'limit_predict_batches': 1.0,
    'limit_test_batches': 1.0,
    'limit_train_batches': 1.0,
    'limit_val_batches': 1.0,
    'log_every_n_steps': 50,
    'log_gpu_memory': None,
    'logger': True,
    'loss_type': 'dice',
    'lr': 0.0001,
    'max_epochs': None,
    'max_steps': None,
    'max_time': None,
    'min_epochs': None,
    'min_steps': None,
    'model_path': 'SHAPENET_VOXEL',
    'move_metrics_to_cpu': False,
    'multiple_trainloader_mode': 'max_size_cycle',
    'num_nodes': 1,
    'num_processes': 1,
    'num_sanity_val_steps': 2,
    'num_workers': 8,
    'overfit_batches': 0.0,
    'plugins': None,
    'precision': 32,
    'prepare_data_per_node': True,
    'process_position': 0,
    'profiler': None,
    'progress_bar_refresh_rate': None,
    'reload_dataloaders_every_epoch': False,
    'replace_sampler_ddp': True,
    'resume_from_checkpoint': None,
    'sample_batch_num': 0,
    'sched_factor': 1,
    'seed': 0,
    'stochastic_weight_avg': False,
    'sync_batchnorm': False,
    'terminate_on_nan': False,
    'threshold': 0.5,
    'tpu_cores': None,
    'track_grad_norm': -1,
    'train_batch_size': 8,
    'transformer_config': 'config/3d-retr-s.yaml',
    'truncated_bptt_steps': None,
    'val_batch_size': 8,
    'val_check_interval': 1.0,
    'view_num': 1,
    'weights_save_path': None,
    'weights_summary': 'top'}
Global seed set to 0
{   'decoder_depth': 6,
    'decoder_dim': 192,
    'decoder_dropout': 0.4,
    'decoder_heads': 3,
    'decoder_model': 'cnn',
    'encoder_dropout': 0.4,
    'encoder_model': 'vit_deit_tiny_distilled_patch16_224',
    'num_cnn_layers': 3,
    'num_resnet_blocks': 2,
    'patch_num': 4,
    'voxel_size': 32}
Ignored parameter "head.weight" on loading
Ignored parameter "head.bias" on loading
Ignored parameter "head_dist.weight" on loading
Ignored parameter "head_dist.bias" on loading
Image2Voxel(
  (encoder): VisionTransformerEncoder(
    (model): DistilledVisionTransformer(
      (patch_embed): PatchEmbed(
        (proj): Conv2d(3, 192, kernel_size=(16, 16), stride=(16, 16))
      )
      (pos_drop): Dropout(p=0.0, inplace=False)
      (blocks): ModuleList(
        (0): Block(
          (norm1): LayerNorm((192,), eps=1e-06, elementwise_affine=True)
          (attn): Attention(
            (qkv): Linear(in_features=192, out_features=576, bias=True)
            (attn_drop): Dropout(p=0.4, inplace=False)
            (proj): Linear(in_features=192, out_features=192, bias=True)
            (proj_drop): Dropout(p=0.0, inplace=False)
          )
          (drop_path): Identity()
          (norm2): LayerNorm((192,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=192, out_features=768, bias=True)
            (act): GELU()
            (fc2): Linear(in_features=768, out_features=192, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
        )
        (1): Block(
          (norm1): LayerNorm((192,), eps=1e-06, elementwise_affine=True)
          (attn): Attention(
            (qkv): Linear(in_features=192, out_features=576, bias=True)
            (attn_drop): Dropout(p=0.4, inplace=False)
            (proj): Linear(in_features=192, out_features=192, bias=True)
            (proj_drop): Dropout(p=0.0, inplace=False)
          )
          (drop_path): Identity()
          (norm2): LayerNorm((192,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=192, out_features=768, bias=True)
            (act): GELU()
            (fc2): Linear(in_features=768, out_features=192, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
        )
        (2): Block(
          (norm1): LayerNorm((192,), eps=1e-06, elementwise_affine=True)
          (attn): Attention(
            (qkv): Linear(in_features=192, out_features=576, bias=True)
            (attn_drop): Dropout(p=0.4, inplace=False)
            (proj): Linear(in_features=192, out_features=192, bias=True)
            (proj_drop): Dropout(p=0.0, inplace=False)
          )
          (drop_path): Identity()
          (norm2): LayerNorm((192,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=192, out_features=768, bias=True)
            (act): GELU()
            (fc2): Linear(in_features=768, out_features=192, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
        )
        (3): Block(
          (norm1): LayerNorm((192,), eps=1e-06, elementwise_affine=True)
          (attn): Attention(
            (qkv): Linear(in_features=192, out_features=576, bias=True)
            (attn_drop): Dropout(p=0.4, inplace=False)
            (proj): Linear(in_features=192, out_features=192, bias=True)
            (proj_drop): Dropout(p=0.0, inplace=False)
          )
          (drop_path): Identity()
          (norm2): LayerNorm((192,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=192, out_features=768, bias=True)
            (act): GELU()
            (fc2): Linear(in_features=768, out_features=192, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
        )
        (4): Block(
          (norm1): LayerNorm((192,), eps=1e-06, elementwise_affine=True)
          (attn): Attention(
            (qkv): Linear(in_features=192, out_features=576, bias=True)
            (attn_drop): Dropout(p=0.4, inplace=False)
            (proj): Linear(in_features=192, out_features=192, bias=True)
            (proj_drop): Dropout(p=0.0, inplace=False)
          )
          (drop_path): Identity()
          (norm2): LayerNorm((192,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=192, out_features=768, bias=True)
            (act): GELU()
            (fc2): Linear(in_features=768, out_features=192, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
        )
        (5): Block(
          (norm1): LayerNorm((192,), eps=1e-06, elementwise_affine=True)
          (attn): Attention(
            (qkv): Linear(in_features=192, out_features=576, bias=True)
            (attn_drop): Dropout(p=0.4, inplace=False)
            (proj): Linear(in_features=192, out_features=192, bias=True)
            (proj_drop): Dropout(p=0.0, inplace=False)
          )
          (drop_path): Identity()
          (norm2): LayerNorm((192,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=192, out_features=768, bias=True)
            (act): GELU()
            (fc2): Linear(in_features=768, out_features=192, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
        )
        (6): Block(
          (norm1): LayerNorm((192,), eps=1e-06, elementwise_affine=True)
          (attn): Attention(
            (qkv): Linear(in_features=192, out_features=576, bias=True)
            (attn_drop): Dropout(p=0.4, inplace=False)
            (proj): Linear(in_features=192, out_features=192, bias=True)
            (proj_drop): Dropout(p=0.0, inplace=False)
          )
          (drop_path): Identity()
          (norm2): LayerNorm((192,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=192, out_features=768, bias=True)
            (act): GELU()
            (fc2): Linear(in_features=768, out_features=192, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
        )
        (7): Block(
          (norm1): LayerNorm((192,), eps=1e-06, elementwise_affine=True)
          (attn): Attention(
            (qkv): Linear(in_features=192, out_features=576, bias=True)
            (attn_drop): Dropout(p=0.4, inplace=False)
            (proj): Linear(in_features=192, out_features=192, bias=True)
            (proj_drop): Dropout(p=0.0, inplace=False)
          )
          (drop_path): Identity()
          (norm2): LayerNorm((192,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=192, out_features=768, bias=True)
            (act): GELU()
            (fc2): Linear(in_features=768, out_features=192, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
        )
        (8): Block(
          (norm1): LayerNorm((192,), eps=1e-06, elementwise_affine=True)
          (attn): Attention(
            (qkv): Linear(in_features=192, out_features=576, bias=True)
            (attn_drop): Dropout(p=0.4, inplace=False)
            (proj): Linear(in_features=192, out_features=192, bias=True)
            (proj_drop): Dropout(p=0.0, inplace=False)
          )
          (drop_path): Identity()
          (norm2): LayerNorm((192,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=192, out_features=768, bias=True)
            (act): GELU()
            (fc2): Linear(in_features=768, out_features=192, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
        )
        (9): Block(
          (norm1): LayerNorm((192,), eps=1e-06, elementwise_affine=True)
          (attn): Attention(
            (qkv): Linear(in_features=192, out_features=576, bias=True)
            (attn_drop): Dropout(p=0.4, inplace=False)
            (proj): Linear(in_features=192, out_features=192, bias=True)
            (proj_drop): Dropout(p=0.0, inplace=False)
          )
          (drop_path): Identity()
          (norm2): LayerNorm((192,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=192, out_features=768, bias=True)
            (act): GELU()
            (fc2): Linear(in_features=768, out_features=192, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
        )
        (10): Block(
          (norm1): LayerNorm((192,), eps=1e-06, elementwise_affine=True)
          (attn): Attention(
            (qkv): Linear(in_features=192, out_features=576, bias=True)
            (attn_drop): Dropout(p=0.4, inplace=False)
            (proj): Linear(in_features=192, out_features=192, bias=True)
            (proj_drop): Dropout(p=0.0, inplace=False)
          )
          (drop_path): Identity()
          (norm2): LayerNorm((192,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=192, out_features=768, bias=True)
            (act): GELU()
            (fc2): Linear(in_features=768, out_features=192, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
        )
        (11): Block(
          (norm1): LayerNorm((192,), eps=1e-06, elementwise_affine=True)
          (attn): Attention(
            (qkv): Linear(in_features=192, out_features=576, bias=True)
            (attn_drop): Dropout(p=0.4, inplace=False)
            (proj): Linear(in_features=192, out_features=192, bias=True)
            (proj_drop): Dropout(p=0.0, inplace=False)
          )
          (drop_path): Identity()
          (norm2): LayerNorm((192,), eps=1e-06, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=192, out_features=768, bias=True)
            (act): GELU()
            (fc2): Linear(in_features=768, out_features=192, bias=True)
            (drop): Dropout(p=0.0, inplace=False)
          )
        )
      )
      (norm): LayerNorm((192,), eps=1e-06, elementwise_affine=True)
      (pre_logits): Identity()
    )
  )
  (decoder): VoxelDecoderCNN(
    (emb): Embedding(64, 192)
    (transformer): AttentionLayers(
      (layers): ModuleList(
        (0): ModuleList(
          (0): LayerNorm((192,), eps=1e-05, elementwise_affine=True)
          (1): Attention(
            (to_q): Linear(in_features=192, out_features=192, bias=False)
            (to_k): Linear(in_features=192, out_features=192, bias=False)
            (to_v): Linear(in_features=192, out_features=192, bias=False)
            (dropout): Dropout(p=0.4, inplace=False)
            (to_out): Linear(in_features=192, out_features=192, bias=True)
          )
          (2): Residual()
        )
        (1): ModuleList(
          (0): LayerNorm((192,), eps=1e-05, elementwise_affine=True)
          (1): Attention(
            (to_q): Linear(in_features=192, out_features=192, bias=False)
            (to_k): Linear(in_features=192, out_features=192, bias=False)
            (to_v): Linear(in_features=192, out_features=192, bias=False)
            (dropout): Dropout(p=0.4, inplace=False)
            (to_out): Linear(in_features=192, out_features=192, bias=True)
          )
          (2): Residual()
        )
        (2): ModuleList(
          (0): LayerNorm((192,), eps=1e-05, elementwise_affine=True)
          (1): FeedForward(
            (net): Sequential(
              (0): Sequential(
                (0): Linear(in_features=192, out_features=768, bias=True)
                (1): GELU()
              )
              (1): Dropout(p=0.0, inplace=False)
              (2): Linear(in_features=768, out_features=192, bias=True)
            )
          )
          (2): Residual()
        )
        (3): ModuleList(
          (0): LayerNorm((192,), eps=1e-05, elementwise_affine=True)
          (1): Attention(
            (to_q): Linear(in_features=192, out_features=192, bias=False)
            (to_k): Linear(in_features=192, out_features=192, bias=False)
            (to_v): Linear(in_features=192, out_features=192, bias=False)
            (dropout): Dropout(p=0.4, inplace=False)
            (to_out): Linear(in_features=192, out_features=192, bias=True)
          )
          (2): Residual()
        )
        (4): ModuleList(
          (0): LayerNorm((192,), eps=1e-05, elementwise_affine=True)
          (1): Attention(
            (to_q): Linear(in_features=192, out_features=192, bias=False)
            (to_k): Linear(in_features=192, out_features=192, bias=False)
            (to_v): Linear(in_features=192, out_features=192, bias=False)
            (dropout): Dropout(p=0.4, inplace=False)
            (to_out): Linear(in_features=192, out_features=192, bias=True)
          )
          (2): Residual()
        )
        (5): ModuleList(
          (0): LayerNorm((192,), eps=1e-05, elementwise_affine=True)
          (1): FeedForward(
            (net): Sequential(
              (0): Sequential(
                (0): Linear(in_features=192, out_features=768, bias=True)
                (1): GELU()
              )
              (1): Dropout(p=0.0, inplace=False)
              (2): Linear(in_features=768, out_features=192, bias=True)
            )
          )
          (2): Residual()
        )
        (6): ModuleList(
          (0): LayerNorm((192,), eps=1e-05, elementwise_affine=True)
          (1): Attention(
            (to_q): Linear(in_features=192, out_features=192, bias=False)
            (to_k): Linear(in_features=192, out_features=192, bias=False)
            (to_v): Linear(in_features=192, out_features=192, bias=False)
            (dropout): Dropout(p=0.4, inplace=False)
            (to_out): Linear(in_features=192, out_features=192, bias=True)
          )
          (2): Residual()
        )
        (7): ModuleList(
          (0): LayerNorm((192,), eps=1e-05, elementwise_affine=True)
          (1): Attention(
            (to_q): Linear(in_features=192, out_features=192, bias=False)
            (to_k): Linear(in_features=192, out_features=192, bias=False)
            (to_v): Linear(in_features=192, out_features=192, bias=False)
            (dropout): Dropout(p=0.4, inplace=False)
            (to_out): Linear(in_features=192, out_features=192, bias=True)
          )
          (2): Residual()
        )
        (8): ModuleList(
          (0): LayerNorm((192,), eps=1e-05, elementwise_affine=True)
          (1): FeedForward(
            (net): Sequential(
              (0): Sequential(
                (0): Linear(in_features=192, out_features=768, bias=True)
                (1): GELU()
              )
              (1): Dropout(p=0.0, inplace=False)
              (2): Linear(in_features=768, out_features=192, bias=True)
            )
          )
          (2): Residual()
        )
        (9): ModuleList(
          (0): LayerNorm((192,), eps=1e-05, elementwise_affine=True)
          (1): Attention(
            (to_q): Linear(in_features=192, out_features=192, bias=False)
            (to_k): Linear(in_features=192, out_features=192, bias=False)
            (to_v): Linear(in_features=192, out_features=192, bias=False)
            (dropout): Dropout(p=0.4, inplace=False)
            (to_out): Linear(in_features=192, out_features=192, bias=True)
          )
          (2): Residual()
        )
        (10): ModuleList(
          (0): LayerNorm((192,), eps=1e-05, elementwise_affine=True)
          (1): Attention(
            (to_q): Linear(in_features=192, out_features=192, bias=False)
            (to_k): Linear(in_features=192, out_features=192, bias=False)
            (to_v): Linear(in_features=192, out_features=192, bias=False)
            (dropout): Dropout(p=0.4, inplace=False)
            (to_out): Linear(in_features=192, out_features=192, bias=True)
          )
          (2): Residual()
        )
        (11): ModuleList(
          (0): LayerNorm((192,), eps=1e-05, elementwise_affine=True)
          (1): FeedForward(
            (net): Sequential(
              (0): Sequential(
                (0): Linear(in_features=192, out_features=768, bias=True)
                (1): GELU()
              )
              (1): Dropout(p=0.0, inplace=False)
              (2): Linear(in_features=768, out_features=192, bias=True)
            )
          )
          (2): Residual()
        )
        (12): ModuleList(
          (0): LayerNorm((192,), eps=1e-05, elementwise_affine=True)
          (1): Attention(
            (to_q): Linear(in_features=192, out_features=192, bias=False)
            (to_k): Linear(in_features=192, out_features=192, bias=False)
            (to_v): Linear(in_features=192, out_features=192, bias=False)
            (dropout): Dropout(p=0.4, inplace=False)
            (to_out): Linear(in_features=192, out_features=192, bias=True)
          )
          (2): Residual()
        )
        (13): ModuleList(
          (0): LayerNorm((192,), eps=1e-05, elementwise_affine=True)
          (1): Attention(
            (to_q): Linear(in_features=192, out_features=192, bias=False)
            (to_k): Linear(in_features=192, out_features=192, bias=False)
            (to_v): Linear(in_features=192, out_features=192, bias=False)
            (dropout): Dropout(p=0.4, inplace=False)
            (to_out): Linear(in_features=192, out_features=192, bias=True)
          )
          (2): Residual()
        )
        (14): ModuleList(
          (0): LayerNorm((192,), eps=1e-05, elementwise_affine=True)
          (1): FeedForward(
            (net): Sequential(
              (0): Sequential(
                (0): Linear(in_features=192, out_features=768, bias=True)
                (1): GELU()
              )
              (1): Dropout(p=0.0, inplace=False)
              (2): Linear(in_features=768, out_features=192, bias=True)
            )
          )
          (2): Residual()
        )
        (15): ModuleList(
          (0): LayerNorm((192,), eps=1e-05, elementwise_affine=True)
          (1): Attention(
            (to_q): Linear(in_features=192, out_features=192, bias=False)
            (to_k): Linear(in_features=192, out_features=192, bias=False)
            (to_v): Linear(in_features=192, out_features=192, bias=False)
            (dropout): Dropout(p=0.4, inplace=False)
            (to_out): Linear(in_features=192, out_features=192, bias=True)
          )
          (2): Residual()
        )
        (16): ModuleList(
          (0): LayerNorm((192,), eps=1e-05, elementwise_affine=True)
          (1): Attention(
            (to_q): Linear(in_features=192, out_features=192, bias=False)
            (to_k): Linear(in_features=192, out_features=192, bias=False)
            (to_v): Linear(in_features=192, out_features=192, bias=False)
            (dropout): Dropout(p=0.4, inplace=False)
            (to_out): Linear(in_features=192, out_features=192, bias=True)
          )
          (2): Residual()
        )
        (17): ModuleList(
          (0): LayerNorm((192,), eps=1e-05, elementwise_affine=True)
          (1): FeedForward(
            (net): Sequential(
              (0): Sequential(
                (0): Linear(in_features=192, out_features=768, bias=True)
                (1): GELU()
              )
              (1): Dropout(p=0.0, inplace=False)
              (2): Linear(in_features=768, out_features=192, bias=True)
            )
          )
          (2): Residual()
        )
      )
    )
    (decoder): Sequential(
      (0): Conv3d(192, 64, kernel_size=(1, 1, 1), stride=(1, 1, 1))
      (1): ResBlock(
        (net): Sequential(
          (0): Conv3d(64, 64, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1))
          (1): ReLU()
          (2): Conv3d(64, 64, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1))
          (3): ReLU()
          (4): Conv3d(64, 64, kernel_size=(1, 1, 1), stride=(1, 1, 1))
        )
      )
      (2): ResBlock(
        (net): Sequential(
          (0): Conv3d(64, 64, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1))
          (1): ReLU()
          (2): Conv3d(64, 64, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1))
          (3): ReLU()
          (4): Conv3d(64, 64, kernel_size=(1, 1, 1), stride=(1, 1, 1))
        )
      )
      (3): Sequential(
        (0): ConvTranspose3d(64, 64, kernel_size=(4, 4, 4), stride=(2, 2, 2), padding=(1, 1, 1))
        (1): ReLU()
      )
      (4): Sequential(
        (0): ConvTranspose3d(64, 64, kernel_size=(4, 4, 4), stride=(2, 2, 2), padding=(1, 1, 1))
        (1): ReLU()
      )
      (5): Sequential(
        (0): ConvTranspose3d(64, 64, kernel_size=(4, 4, 4), stride=(2, 2, 2), padding=(1, 1, 1))
        (1): ReLU()
      )
      (6): Conv3d(64, 1, kernel_size=(1, 1, 1), stride=(1, 1, 1))
    )
    (layer_norm): LayerNorm((192,), eps=1e-05, elementwise_affine=True)
    (to_patch): Linear(in_features=192, out_features=512, bias=True)
  )
)
/home/ubuntu/anaconda3/envs/3d-retr/lib/python3.6/site-packages/pytorch_lightning/utilities/distributed.py:69: UserWarning: You requested multiple GPUs but did not specify a backend, e.g. `Trainer(accelerator="dp"|"ddp"|"ddp2")`. Setting `accelerator="ddp_spawn"` for you.
  warnings.warn(*args, **kwargs)
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
Global seed set to 0
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/2
Global seed set to 0
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/2

  | Name    | Type                     | Params
-----------------------------------------------------
0 | encoder | VisionTransformerEncoder | 5.5 M 
1 | decoder | VoxelDecoderCNN          | 4.9 M 
-----------------------------------------------------
10.4 M    Trainable params
0         Non-trainable params
10.4 M    Total params
41.761    Total estimated model params size (MB)
Validation sanity check: 0it [00:00, ?it/s]/home/ubuntu/anaconda3/envs/3d-retr/lib/python3.6/site-packages/pytorch_lightning/utilities/distributed.py:69: UserWarning: num_workers>0, persistent_workers=False, and accelerator=ddp_spawn may result in data loading bottlenecks. Consider setting persistent_workers=True (this is a limitation of Python .spawn() and PyTorch)
  warnings.warn(*args, **kwargs)
Validation sanity check:   0%|                                                                                                         | 0/2 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 155, in <module>
    trainer.fit(model, train_loader, val_loader)
  File "/home/ubuntu/anaconda3/envs/3d-retr/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 458, in fit
    self._run(model)
  File "/home/ubuntu/anaconda3/envs/3d-retr/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 756, in _run
    self.dispatch()
  File "/home/ubuntu/anaconda3/envs/3d-retr/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 797, in dispatch
    self.accelerator.start_training(self)
  File "/home/ubuntu/anaconda3/envs/3d-retr/lib/python3.6/site-packages/pytorch_lightning/accelerators/accelerator.py", line 96, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/ubuntu/anaconda3/envs/3d-retr/lib/python3.6/site-packages/pytorch_lightning/plugins/training_type/ddp_spawn.py", line 122, in start_training
    mp.spawn(self.new_process, **self.mp_spawn_kwargs)
  File "/home/ubuntu/anaconda3/envs/3d-retr/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/ubuntu/anaconda3/envs/3d-retr/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/ubuntu/anaconda3/envs/3d-retr/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/3d-retr/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/ubuntu/anaconda3/envs/3d-retr/lib/python3.6/site-packages/pytorch_lightning/plugins/training_type/ddp_spawn.py", line 172, in new_process
    results = trainer.run_stage()
  File "/home/ubuntu/anaconda3/envs/3d-retr/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 807, in run_stage
    return self.run_train()
  File "/home/ubuntu/anaconda3/envs/3d-retr/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 842, in run_train
    self.run_sanity_check(self.lightning_module)
  File "/home/ubuntu/anaconda3/envs/3d-retr/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1107, in run_sanity_check
    self.run_evaluation()
  File "/home/ubuntu/anaconda3/envs/3d-retr/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 949, in run_evaluation
    for batch_idx, batch in enumerate(dataloader):
  File "/home/ubuntu/anaconda3/envs/3d-retr/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/ubuntu/anaconda3/envs/3d-retr/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/ubuntu/anaconda3/envs/3d-retr/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/ubuntu/anaconda3/envs/3d-retr/lib/python3.6/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/3d-retr/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ubuntu/anaconda3/envs/3d-retr/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/anaconda3/envs/3d-retr/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/YaoXinSheng/3D-RETR-main/src/data/datasets.py", line 25, in __getitem__
    return self._dataset[self._indices[index].item()]
  File "/home/ubuntu/YaoXinSheng/3D-RETR-main/src/data/datasets.py", line 109, in __getitem__
    image = self._image_transforms(image)
  File "/home/ubuntu/YaoXinSheng/3D-RETR-main/src/data/transforms.py", line 32, in __call__
    rendering_images = t(rendering_images)
TypeError: 'bytes' object is not callable
`
